# THIS IS A NEW WORKFLOW TO CREATE A NEW SPACE ON QLIKCLOUD

name: Create New Space

# Controls when the action will run. 
on:
  #push:
    #branches: main
    #paths: '**.ps1'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "create_new_space"
  create_new_space:

    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # RUN POWERSHELL SCRIPT
      - name: RUN POWERSHELL SCRIPT

        # USE POWERSHELL SHELL
      - shell: pwsh

        # INCLUDE GITHUB SECRET FOR THE REQUIRED API KEY
        env:
          QCS_SERVER_URL: "https://sensetest.eu.qlikcloud.com"
          QCS_SERVER_API_KEY: ${{ secrets.SENSETEST_EU_MJQ_API_KEY }}
        run: |
          Write-Host "$env:QCS_SERVER_URL"
          Write-Host "$env:QCS_SERVER_API_KEY"

        # USE RUN COMMAND TO TELL POWERSHELL WHAT TO ACTUALLY DO - WHICH IS RUN THIS PS1
        #run: pwsh -command ".\CreateNewSpaces\Qlik@Qlik_TEST_1.ps1"
