# THIS IS A NEW WORKFLOW TO CREATE A NEW SPACE ON QLIKCLOUD

name: Create New Space On QCS

# SET ACTION TO ONLY RUN ON A PUSH TO MAIN WHERE THE FILE IS A PS1 FILE IN THE CreateNewSpaces FOLDER
on:
  push:
    branches: main    
    paths: 'CreateNewSpaces/**.ps1'

  # ALLOWS YOU TO RUN THIS WORKFLOW MANUALLY FROM THE ACTIONS TAB
  workflow_dispatch:

# A WORKFLOW RUN IS MADE UP OF ONE OR MORE JOBS THAT CAN RUN SEQUENTIALLY OR IN PARALLEL
jobs:

  # THIS WORKFLOW CONTAINS A SINGLE JOB CALLED "create_new_space"
  create_new_space:
    
    # NAME OF THE JOB
    name: CREATE NEW SPACE

    # THE TYPE OF RUNNER THAT THE JOB WILL RUN ON
    runs-on: windows-latest
    
    # STEPS REPRESENT A SEQUENCE OF TASKS THAT WILL BE EXECUTED AS PART OF THE JOB
    steps:

      # CHECKS-OUT YOUR REPOSITORY UNDER $GITHUB_WORKSPACE, SO YOUR JOB CAN ACCESS IT
      - name: CHECKOUT REPO
      - uses: actions/checkout@v2

      # RUN POWERSHELL SCRIPT
      - name: RUN POWERSHELL SCRIPT

        # USE POWERSHELL SHELL
        shell: pwsh

        # INCLUDE GITHUB SECRET AS POWERSHELL ENV VARIABLE FOR THE REQUIRED API KEY
        env:
          QCS_SERVER_URL: ${{ secrets.SENSETEST_EU_URL }}
          QCS_SERVER_API_KEY: ${{ secrets.SENSETEST_EU_MJQ_API_KEY }}

        # USE RUN COMMAND TO TELL POWERSHELL WHAT TO ACTUALLY DO - WHICH IS RUN THIS PS1
        run: pwsh -command ".\CreateNewSpaces\Qlik@Qlik_TEST_1.ps1"
