# This is a basic workflow to help you get started with Actions

name: Create_Space_SenseTest.EU.QlikCloud

# Controls when the action will run. 
on:
  push:
    branches: main
    paths: '**.ps1'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "create_new_space"
  create_new_space:

    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # RUN POWERSHELL SCRIPT
      - name: RUN POWERSHELL SCRIPT
      - shell: pwsh
        env:
          API_KEY: ${{ secrets.SENSETEST_EU_MJQ_API_KEY }}
        run: pwsh -command ".\CreateNewSpaces\Qlik@Qlik_TEST_1.ps1"
